name: Deploy WebSharper SPA

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Add WebSharper Feed
        run: |
          dotnet nuget add source \
            --username fatihaBizermimne \
            --password ${{ secrets.WEBSHARPER_FEED }} \
            --store-password-in-clear-text \
            --name websharper \
            https://nuget.websharper.com/feed/nuget/index.json

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
