name: Deploy WebSharper SPA

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Verify critical files
        run: |
          [ -f wwwroot/StudentContact.js ] || { echo "Error: StudentContact.js missing"; exit 1; }
          [ -f wwwroot/index.html ] || { echo "Error: index.html missing"; exit 1; }
          echo "All required files present"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: wwwroot
          keep_files: false
